#! /bin/sh
#
# stocks-monitor        Start/stop stocks-monitor
#

### BEGIN INIT INFO
# Provides:          stocks-monitor
# Required-Start:    $remote_fs $network $named $time
# Required-Stop:     $remote_fs $network $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts stocks-monitor
# Description:       Starts stocks-monitor, mostly Django-powered stocks-monitor.
### END INIT INFO

RUN=$(dirname $(readlink -f "$0"))/../init.sh

test -e $RUN || exit 0

start()
{
    $RUN >> /dev/null
}

stop()
{
    $RUN >> /dev/null
}

case "$1" in
    start)
    echo -n "Starting stocks-monitor..."
    start &
    ;;
    stop)
    echo -n "Stopping stocks-monitor..."
    stop &
    ;;
    *)
    echo "Usage: $0 {start|stop}" >&2
    exit 1
    ;;
esac

if [ $? -eq 0 ]; then
    echo .
else
    echo " failed!"
fi

exit 0

