#! /bin/sh
#
# stocks-monitor        Start/stop stocks-monitor
#

### BEGIN INIT INFO
# Provides:          stocks-monitor
# Required-Start:    $remote_fs $network $named $time
# Required-Stop:     $remote_fs $network $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts stocks-monitor
# Description:       Starts stocks-monitor, mostly Django-powered stocks-monitor.
### END INIT INFO

BASEDIR=$(dirname $(readlink -f "$0"))/..

RUN=$BASEDIR/init.sh
PID_FILE=$BASEDIR/tmp/pids/service.pid

test -e $RUN || exit 0

start_force()
{
    $RUN 1>/dev/null 2>&1 &
    echo $! > $PID_FILE
}

start()
{
    # Only start if not yet started
    PID=$(cat $PID_FILE)

    if [ ! -z $PID ]; then
        kill -0 $PID
        if [ $? -ne 0 ]; then
            start_force
        fi
    else
        start_force
    fi
}

stop()
{
    kill -9 $(cat $PID_FILE)
    rm $PID_FILE
}

case "$1" in
    start)
    echo -n "Starting stocks-monitor..."
    start
    ;;
    stop)
    echo -n "Stopping stocks-monitor..."
    stop
    ;;
    *)
    echo "Usage: $0 {start|stop}" >&2
    exit 1
    ;;
esac

if [ $? -eq 0 ]; then
    echo .
else
    echo " failed!"
fi

exit 0

